/*Practical : 12*/

CREATE TABLE EMPLOYEE_12 (EID INT, ENAME VARCHAR(50),DEPARTMENT VARCHAR(50),
SALARY INT,JOININGDATE DATETIME,CITY VARCHAR(50))

INSERT INTO EMPLOYEE_12 VALUES
(101, 'Rahul', 'Admin', 56000, '1-Jan-90', 'Rajkot'),
(102, 'Hardik', 'IT', 18000, '25-Sep-90', 'Ahmedabad'),
(103, 'Bhavin', 'HR', 25000, '14-May-91' ,'Baroda'),
(104, 'Bhoomi', 'Admin', 39000, '8-Feb-91','Rajkot'),
(105, 'Rohit' ,'IT', 17000, '23-Jul-90' ,'Jamnagar'),
(106, 'Priya', 'IT', 9000, '18-Oct-90', 'Ahmedabad'),
(107, 'Neha', 'HR', 34000, '25-Dec-91' ,'Rajkot')

SELECT * FROM EMPLOYEE_12
/*Part : A*/

SELECT MAX(SALARY) AS MAXIMUM,MIN(SALARY) AS MINIMUM, SUM(SALARY) AS TOTAL_SAL,
AVG(SALARY) AS AVG_SAL FROM EMPLOYEE_12

SELECT COUNT(EID) AS TOTAL_NUM_EMPLOYEEE FROM EMPLOYEE_12

SELECT MAX(SALARY) AS MAX_IT FROM EMPLOYEE_12 WHERE DEPARTMENT='IT'

SELECT COUNT(DISTINCT(CITY)) AS TOTAL_DISTINCT_CITY FROM EMPLOYEE_12

SELECT CITY, COUNT(*) AS TOTAL_EMPLOYESS FROM EMPLOYEE_12 GROUP BY CITY ORDER BY TOTAL_EMPLOYESS;

SELECT CITY,COUNT(CITY) AS TOTAL_EMPLOYES_FROM FROM EMPLOYEE_12 GROUP BY CITY HAVING COUNT(CITY) > 1

SELECT DEPARTMENT, SUM(SALARY) AS DEPARTMENT_WISE_SUM FROM EMPLOYEE_12 GROUP BY DEPARTMENT

SELECT AVG(SALARY) AS DEPARTMENT_WISE_SUM FROM EMPLOYEE_12 GROUP BY DEPARTMENT

SELECT MIN(SALARY) AS MIN_SALARY_AHEM FROM EMPLOYEE_12 WHERE CITY='Ahmedabad'


SELECT DEPARTMENT, SUM(SALARY) AS DEPARTMENT_WISE_SUM FROM EMPLOYEE_12 
WHERE CITY='Rajkot'  GROUP BY DEPARTMENT
HAVING SUM(SALARY) > 50000 

/*Part : B*/

SELECT COUNT(EID) AS NO_EMP FROM EMPLOYEE_12 WHERE CITY='Rajkot'

SELECT MAX(salary) - MIN(salary) AS DIFFERENCE
FROM EMPLOYEE_12;

SELECT COUNT(*) AS total_employees FROM EMPLOYEE_12 WHERE JOININGDATE < '1991-01-01';

SELECT DEPARTMENT, SUM(SALARY) AS total_salary FROM EMPLOYEE_12
GROUP BY DEPARTMENT HAVING SUM(salary) > 35000 ORDER BY total_salary;

SELECT DEPARTMENT FROM EMPLOYEE_12 
GROUP BY DEPARTMENT HAVING COUNT(*) > 2;

/*Part : C*/

SELECT COUNT(EID) AS NO_EMP FROM EMPLOYEE_12 WHERE CITY='Rajkot' or CITY='Baroda'

SELECT MAX(salary) - MIN(salary) AS DIFFERENCE
FROM EMPLOYEE_12;

SELECT COUNT(*) AS total_employees FROM EMPLOYEE_12 WHERE JOININGDATE < '1991-01-01' and DEPARTMENT='IT';

SELECT DEPARTMENT, SUM(SALARY) AS total_salary
FROM EMPLOYEE_12
GROUP BY DEPARTMENT HAVING SUM(salary) > 35000 ORDER BY total_salary DESC;
