/*practical - 8
part - A*/

select len(null), len('  hello  '), len('')
select lower('meet'), UPPER('meet')
select SUBSTRING('meet',1,3)
select SUBSTRING('meet kacha',3,10)
select REPLACE('abc123efg','123','XYZ'),REPLACE('abcabcabc','c','5')
select ASCII ('a'),ASCII ('A'),ASCII ('z'), ASCII ('Z'), ASCII (0),ASCII (9)
select CHAR(97), CHAR(65), CHAR(122), CHAR(90), CHAR(48), CHAR(57)
SELECT LTRIM('  HELLO WORLD     ')
SELECT RTRIM('  HELLO WORLD     ')
SELECT LEFT('SQL Server', 4),RIGHT('SQL Server', 5) 
SELECT CAST('1234.56' AS NUMERIC)
SELECT CONVERT(NUMERIC, '1234.56')
SELECT CAST('10.58' AS FLOAT)
SELECT CONVERT(FLOAT, '10.58')
SELECT CONCAT('          ','NAMRA')
SELECT 'NAMRA' + 'PITHWA'
SELECT CONCAT('NAMRA','PITHWA')
SELECT REVERSE('Darshan')
SELECT REPLICATE('Namra', 3)

/*Part : B*/

SELECT LEN(FIRSTNAME),LEN(LASTNAME) FROM STUDENT
SELECT LOWER(FIRSTNAME),LOWER(LASTNAME) FROM STUDENT
SELECT UPPER(FIRSTNAME),UPPER(LASTNAME) FROM STUDENT
SELECT SUBSTRING(FIRSTNAME,1,3) FROM STUDENT
SELECT *FROM STUDENT
SELECT SUBSTRING(WEBSITE,3,10) FROM STUDENT
SELECT LEFT(WEBSITE, 4),RIGHT(WEBSITE, 5) FROM STUDENT

/*Part : C */

SELECT CONCAT('          ',FIRSTNAME) FROM STUDENT
SELECT FIRSTNAME + LASTNAME FROM STUDENT
SELECT CONCAT(FIRSTNAME,LASTNAME) FROM STUDENT
SELECT * FROM STUDENT
SELECT CAST(STUID AS varchar)+ FIRSTNAME + LASTNAME + WEBSITE + CITY FROM STUDENT
SELECT CONCAT(STUID,FIRSTNAME,LASTNAME,WEBSITE,CITY) FROM STUDENT
SELECT REVERSE(FIRSTNAME)FROM STUDENT
SELECT REPLICATE(FIRSTNAME, 3) FROM STUDENT
