/*Practical : 11*/

CREATE TABLE CRICKET1 (NAME VARCHAR(50),CITY VARCHAR(50),AGE INT)

INSERT INTO CRICKET1 VALUES
('Sachin Tendulkar', 'Mumbai' ,30),
('Rahul Dravid','Bombay', 35),
('M. S. Dhoni' ,'Jharkhand' ,31),
('Suresh Raina' ,'Gujarat' ,30)

SELECT * FROM CRICKET1

/*Part : A*/

SELECT * INTO WORLDCUP FROM CRICKET1
SELECT * FROM WORLDCUP
SELECT NAME,CITY INTO T20 FROM CRICKET1 WHERE 1=0
SELECT * FROM T20
SELECT * INTO IPL FROM CRICKET1 WHERE 1=0
SELECT * FROM IPL
INSERT INTO IPL SELECT * FROM CRICKET1 WHERE NAME LIKE '_A%'AND LEN(NAME) >= 7 ;
SELECT * FROM IPL
DELETE FROM IPL
DELETE FROM CRICKET1 WHERE CITY='Jharkhand'
EXEC sp_rename 'IPL','IPL2018'
SELECT * FROM IPL2018
DROP TABLE T20

/*Part : B*/

CREATE TABLE EMPLOYEE2 (NAME VARCHAR(50),CITY VARCHAR(50),AGE INT)

INSERT INTO EMPLOYEE2 VALUES
('Jay Patel' ,'Rajkot' ,30),
('Rahul Dave' ,'Baroda' ,35),
('Jeet Patel' ,'Surat' ,31),
('Vijay Raval' ,'Rajkot' ,30)

SELECT * FROM EMPLOYEE2
SELECT * INTO EMPLOYEE_DETAIL_1 FROM EMPLOYEE2
SELECT * FROM EMPLOYEE_DETAIL_1
SELECT NAME,CITY INTO EMPLOYE_DATA_2 FROM EMPLOYEE2 WHERE 1=0
SELECT * FROM EMPLOYE_DATA_2
SELECT * INTO EMPLOYEE_INFO_2 FROM EMPLOYEE2 WHERE 1=0
SELECT * FROM EMPLOYEE_INFO_2
INSERT INTO EMPLOYEE_INFO SELECT * FROM EMPLOYEE2 WHERE NAME LIKE '_A%'AND LEN(NAME) >= 7 ;
SELECT * FROM EMPLOYEE_INFO
INSERT INTO EMPLOYEE_INFO SELECT * FROM EMPLOYEE2 WHERE AGE >32 ;
SELECT * FROM EMPLOYEE_INFO

/*Part : C*/

DELETE FROM EMPLOYEE_INFO
SELECT * FROM EMPLOYEE_INFO
DELETE FROM EMPLOYEE2 WHERE CITY='Rajkot'
SELECT * FROM EMPLOYEE2
EXEC sp_rename 'EMPLOYEE2','NEW_EMPLOYEE'
SELECT * FROM NEW_EMPLOYEE
TRUNCATE TABLE NEW_EMPLOYEE
DROP TABLE NEW_EMPLOYEE
SELECT * FROM NEW_EMPLOYEE
