/*Practical : 10*/
CREATE TABLE COMPUTER (RollNo int, Name Varchar(50))

CREATE TABLE ELECTRICAL (RollNo int, Name Varchar(50))

INSERT INTO COMPUTER VALUES (101,'Ajay'),
(109,'Haresh'),
(115,'Manish')

SELECT * FROM COMPUTER

INSERT INTO ELECTRICAL VALUES
(105, 'Ajay'),
(107, 'Mahesh'),
(115, 'Manish')

SELECT * FROM ELECTRICAL

/*Part : A*/

SELECT NAME FROM COMPUTER UNION SELECT NAME FROM ELECTRICAL
SELECT NAME FROM COMPUTER UNION ALL SELECT NAME FROM ELECTRICAL
SELECT NAME FROM COMPUTER INTERSECT SELECT NAME FROM ELECTRICAL
SELECT NAME FROM COMPUTER EXCEPT SELECT NAME FROM ELECTRICAL
SELECT NAME FROM ELECTRICAL EXCEPT SELECT NAME FROM COMPUTER
SELECT * FROM COMPUTER UNION SELECT * FROM ELECTRICAL
SELECT * FROM COMPUTER INTERSECT SELECT * FROM ELECTRICAL

/**/
CREATE TABLE EMPLOYEE1(EID int, Name Varchar(50))

CREATE TABLE COUSTMER (CID int, Name Varchar(50))

INSERT INTO EMPLOYEE1 VALUES
(1, 'Ajay'),
(9, 'Haresh'),
(5, 'Manish')

INSERT INTO COUSTMER VALUES
(5, 'Ajay'),
(7, 'Mahesh'),
(5, 'Manish')

/*Part : B*/

SELECT NAME FROM EMPLOYEE1 UNION SELECT NAME FROM COUSTMER
SELECT NAME FROM EMPLOYEE1 UNION ALL SELECT NAME FROM COUSTMER
SELECT NAME FROM EMPLOYEE1 INTERSECT SELECT NAME FROM COUSTMER
SELECT NAME FROM EMPLOYEE1 EXCEPT SELECT NAME FROM COUSTMER
SELECT NAME FROM COUSTMER EXCEPT SELECT NAME FROM EMPLOYEE1

/*Part : C*/

SELECT NAME,EID FROM EMPLOYEE1 UNION SELECT NAME,CID FROM COUSTMER
SELECT NAME,EID FROM EMPLOYEE1 UNION ALL SELECT NAME,CID FROM COUSTMER
SELECT NAME,EID FROM EMPLOYEE1 INTERSECT SELECT NAME,CID FROM COUSTMER
SELECT NAME,EID FROM EMPLOYEE1 EXCEPT SELECT NAME,CID FROM COUSTMER
SELECT NAME,CID FROM COUSTMER EXCEPT SELECT NAME,EID  FROM EMPLOYEE1
